health-check:
  path: '%health_check_bundle_health_check_path%'
  controller: SmartAssert\HealthCheckBundle\Controller\HealthCheckController::get

status:
  path: '%health_check_bundle_status_path%'
  controller: SmartAssert\HealthCheckBundle\Controller\StatusController::get
