parameters:
  health_check_bundle_health_check_path: '/health-check'
  health_check_bundle_status_path: '/status'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\HealthCheckBundle\Controller\HealthCheckController:
    arguments:
      $serviceStatusInspector: '@smartassert.health_check_bundle.service_status_inspector.health_check'
    tags: ['controller.service_arguments']

  SmartAssert\HealthCheckBundle\Controller\StatusController:
    arguments:
      $serviceStatusInspector: '@smartassert.health_check_bundle.service_status_inspector.status'
    tags: ['controller.service_arguments']

  SmartAssert\DoctrineInspectors\QueryInspector: ~
  SmartAssert\DoctrineInspectors\EntityMappingInspector: ~

  smartassert.health_check_bundle.doctrine_inspectors.query:
    class: SmartAssert\HealthCheckBundle\Services\DoctrineInspector
    arguments:
      $inspector: '@SmartAssert\DoctrineInspectors\QueryInspector'
      $identifier: 'database_connection'
    tags:
      - { name: 'health_check_bundle.component_inspector.health_check' }

  smartassert.health_check_bundle.doctrine_inspectors.entity_mapping:
    class: SmartAssert\HealthCheckBundle\Services\DoctrineInspector
    arguments:
      $inspector: '@SmartAssert\DoctrineInspectors\EntityMappingInspector'
      $identifier: 'database_entities'
    tags:
      - { name: 'health_check_bundle.component_inspector.health_check' }

  SmartAssert\InvokableLogger\ExceptionLogger: ~

  SmartAssert\HealthCheckBundle\Services\ExceptionLogger:
    arguments:
      $invokableExceptionLogger: '@SmartAssert\InvokableLogger\ExceptionLogger'
    tags:
      - { name: 'health_check_bundle.exception_logger.health_check' }
      - { name: 'health_check_bundle.exception_logger.status' }

  smartassert.health_check_bundle.service_status_inspector.health_check:
    class: SmartAssert\ServiceStatusInspector\ServiceStatusInspector
    public: true
    calls:
      - setComponentInspectors: [!tagged { tag: 'health_check_bundle.component_inspector.health_check' }]
      - setExceptionHandlers: [!tagged { tag: 'health_check_bundle.exception_logger.health_check' }]

  smartassert.health_check_bundle.service_status_inspector.status:
    class: SmartAssert\ServiceStatusInspector\ServiceStatusInspector
    public: true
    calls:
      - setComponentInspectors: [!tagged { tag: 'health_check_bundle.component_inspector.status' }]
      - setExceptionHandlers: [!tagged { tag: 'health_check_bundle.exception_logger.status' }]

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true

    Psr\Log\LoggerInterface:
      class: SmartAssert\HealthCheckBundle\Tests\Services\Logger

    Doctrine\ORM\EntityManagerInterface:
      class: SmartAssert\HealthCheckBundle\Tests\Services\EntityManager

    health_check_bundle.test.public_router:
      alias: Symfony\Component\Routing\RouterInterface
      public: true

    health_check_bundle.test.status_inspector.service1:
      class: SmartAssert\ServiceStatusInspector\ComponentInspector
      arguments:
        $identifier: 'service1'
        $isAvailable: true
      tags:
        - { name: 'health_check_bundle.component_inspector.status' }

    health_check_bundle.test.status_inspector.service2:
      class: SmartAssert\ServiceStatusInspector\ComponentInspector
      arguments:
        $identifier: 'service2'
        $isAvailable: false
      tags:
        - { name: 'health_check_bundle.component_inspector.status' }
