parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Log\LoggerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\Logger

  Doctrine\ORM\EntityManagerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\EntityManager

  health_check_bundle.test.public_router:
    alias: Symfony\Component\Routing\RouterInterface
    public: true
