parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\DoctrineInspectors\QueryInspector:
    tags:
      - { name: 'health_check_bundle.component_inspector', key: 'database_connection' }

  SmartAssert\DoctrineInspectors\EntityMappingInspector:
    tags:
      - { name: 'health_check_bundle.component_inspector', key: 'database_entities' }

  SmartAssert\InvokableLogger\ExceptionLogger:
    tags:
      - { name: 'health_check_bundle.exception_logger', key: 'database_entities' }

  SmartAssert\ServiceStatusInspector\ServiceStatusInspectorInterface:
    class: SmartAssert\ServiceStatusInspector\ServiceStatusInspector
    public: true
    calls:
      - setComponentInspectors: [!tagged { tag: 'health_check_bundle.component_inspector', index_by: 'key' }]
      - setExceptionHandlers: [!tagged { tag: 'health_check_bundle.exception_logger', index_by: 'key' }]
