parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Log\LoggerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\Logger

  Doctrine\ORM\EntityManagerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\EntityManager
