services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Log\LoggerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\Logger

  Doctrine\ORM\EntityManagerInterface:
    class: SmartAssert\HealthCheckBundle\Tests\Services\EntityManager

  health_check_bundle.test.public_router:
    alias: Symfony\Component\Routing\RouterInterface
    public: true

  health_check_bundle.test.status_inspector.service1:
    class: SmartAssert\ServiceStatusInspector\ComponentStatusInspector
    arguments:
      $identifier: 'service1'
      $status: true
    tags:
      - { name: 'health_check_bundle.component_inspector.status' }

  health_check_bundle.test.status_inspector.service2:
    class: SmartAssert\ServiceStatusInspector\ComponentStatusInspector
    arguments:
      $identifier: 'service2'
      $status: false
    tags:
      - { name: 'health_check_bundle.component_inspector.status' }

  SmartAssert\HealthCheckBundle\Tests\Services\ExpectedStatusOutputFactory:
    public: true
    arguments:
      $environment: '%env(APP_ENV)%'
      $isReadyParameter: '%health_check_bundle_status_is_ready%'
      $versionParameter: '%health_check_bundle_status_version%'
