parameters:
  health_check_bundle_route_path: '/health-check'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\HealthCheckBundle\Controller\HealthCheckController:
    tags: ['controller.service_arguments']

  SmartAssert\DoctrineInspectors\QueryInspector: ~
  SmartAssert\DoctrineInspectors\EntityMappingInspector: ~

  smartassert.health_check_bundle.doctrine_inspectors.query:
    class: SmartAssert\HealthCheckBundle\Services\DoctrineInspector
    arguments:
      $inspector: '@SmartAssert\DoctrineInspectors\QueryInspector'
      $identifier: 'database_connection'
    tags:
      - { name: 'health_check_bundle.component_inspector' }

  smartassert.health_check_bundle.doctrine_inspectors.entity_mapping:
    class: SmartAssert\HealthCheckBundle\Services\DoctrineInspector
    arguments:
      $inspector: '@SmartAssert\DoctrineInspectors\EntityMappingInspector'
      $identifier: 'database_entities'
    tags:
      - { name: 'health_check_bundle.component_inspector' }

  SmartAssert\InvokableLogger\ExceptionLogger: ~

  SmartAssert\HealthCheckBundle\Services\ExceptionLogger:
    arguments:
      $invokableExceptionLogger: '@SmartAssert\InvokableLogger\ExceptionLogger'
    tags:
      - { name: 'health_check_bundle.exception_logger' }

  SmartAssert\ServiceStatusInspector\ServiceStatusInspectorInterface:
    class: SmartAssert\ServiceStatusInspector\ServiceStatusInspector
    public: true
    calls:
      - setComponentInspectors: [!tagged { tag: 'health_check_bundle.component_inspector', index_by: 'key' }]
      - setExceptionHandlers: [!tagged { tag: 'health_check_bundle.exception_logger', index_by: 'key' }]
