name: standards

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP CS Fixer Dry Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run
        run: composer cs-fixer-dry-run

  phpcs:
    name: PHPCS - PHP ${{ matrix.php }}  symfony/${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.2', '8.3']
        symfony: ['7.0.*', '7.1.*', '7.2.*']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: |
          sed -i 's/"\^7.0 || \^7.1 || \^7.2"/\"${{ matrix.symfony }}"/g' composer.json
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run
        run: composer cs-phpcs
