name: static

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan - PHP ${{ matrix.php }} symfony/${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.1']
        symfony: ['6.2.*', '6.3.*']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: |
          sed -i 's/"\^6.0 || \^6.1 || \^6.2 || \^6.3"/\"${{ matrix.symfony }}"/g' composer.json
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHPStan
        run: composer static-analysis

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color
